### PR TITLE
updated log4net

### PR DESCRIPTION
**Pull request by wjdavis5**

### CODE REVIEW

**Comment by wjdavis5** [comment]
Any update on this?

**Comment by psquickitjayant** [comment]
hey @wjdavis5 , sorry i was busy with other suff. Could you please mention in details, what changes you have made? It seems lot of files are changed or updated.

**Comment by wjdavis5** [comment]
Yes, literally the only thing that was done was to update the log4net nuget package. The reason there are so many changes is b/c this project does not have a `.gitignore` that excludes the binary files and output directories.

**Comment by wjdavis5** [comment]
Any updates available for this?

**Pull request closed without merging**
