### PR TITLE
Added log4net ThreadContext Context Stack support 

### PR DESCRIPTION
**Pull request by PaulDMendoza**
log4net supports  a concept of using stacks in the code so each log statement doesn't have to include contextual information. For example, if processing everything for a user, the block can be wrapped with a stack value with a UserID. 

     using(log4net.ThreadContext.Stacks["NDC"].Push("UserID: 323-3223-dcs3234324"))
     {
          log.Info("This message will get the stack");
           log.Error("So will this message");
      }

http://logging.apache.org/log4net/release/manual/contexts.html

Once this is merged in please update your NuGet feed. 

If someone doesn't use NDC stacks then they won't get an output. I tested this on my log4net account and it worked well.  Notice in the below screenshot the "oops" exception doesn't have an ndcStack value but the entry after (above) does. 

image

This also supports multiple stack values as I added to the test.

image

### CODE REVIEW

**Comment by psquickitjayant** [comment]
I have implemented the support for NDC with more details. NDC stack values are sent as array to Loggly. @PaulDMendoza,  please have a look at https://github.com/psquickitjayant/log4net-loggly/commit/a86d9db2e599eb5cd23dd4edba793b1fc45696ef

**Comment by psquickitjayant** [comment]
hey @PaulDMendoza, I have tested in Loggly Dashboard, NDC Stack does not help too much as we cannot push values in the form of key value pair which can be parsed in Loggly. It is better to use ThreadContext.Properties to add key value pairs in the log so that each ThreadContextProperty can act as an independent json.field in the Loggly field explorer.

**Comment by PaulDMendoza** [comment]
Okay, that's fine. How long will it take to get that change implemented?

**Comment by psquickitjayant** [comment]
I have implemented this at https://github.com/psquickitjayant/log4net-loggly/commit/a08d520cca93c1aafabf71e21ee87d318077fb7c @PaulDMendoza

**Comment by psquickitjayant** [comment]
@PaulDMendoza  I have added support to both ThreadStack and ThreadContext properties. Please have a look at https://github.com/psquickitjayant/log4net-loggly/commit/af87be2bbedcad68fb036d0bb4e815ba2f3b19b5. It supports not only NDC, but all stacks   present in the dictionary.

**Comment by psquickitjayant** [comment]
@PaulDMendoza  I have updated the Nuget package with the ThreadStack support. So closing this one. Thanks.

**Pull request closed without merging**
