### PR TITLE
Updated References

### PR DESCRIPTION
**Pull request by wjdavis5**
I have updated the references for log4net and NewtonSoft.

I also updated your gitignore, so it probably looks like a lot has changed. The only real changes are to the references, and then the removal of a lot of files b/c of the new ignore.... I'll be contacting Loggly support to try and get some traction on this.

### CODE REVIEW

**Comment by mostlyjason** [comment]
Hi we want to look at this but we don't have anyone to test it right now. I'm hoping people can use this PR directly until we get a chance to review and merge it.

**Comment by psquickitjayant** [comment]
I will have it tested and update this weekend.

**Comment by wjdavis5** [comment]
As a quick aside - I've been following the [Log4Net repo here](https://github.com/apache/log4net/pull/16) and it appears they are prepping to (hopefully) very soon release a new version of log4net with DotNetCore support. Once that has been released it'll be awesome to get log4net-loggly appenders ported over. I'll probably do so as soon as that new version hits the shelves.

**Comment by wjdavis5** [comment]
Hello, wanted to ping this thread for an update. Thanks!

**Comment by wjdavis5** [comment]
Any status updates here?

**Pull request closed without merging**
