### PR TITLE
fix for self refrencing bug

### PR DESCRIPTION
**Pull request by giladwe**
added test case for the console.
add fix for the bug, based on this blog post:
https://bobbycannon.com/Post/JsonNetSelfReferencingLoopDetected

### CODE REVIEW

**Comment by psquickitjayant** [comment]
Thanks for the fix @giladwe . I had never tested this.

**Comment by psquickitjayant** [comment]
@giladwe  Well, I have merged this pull request. Still I was thinking of using the following property as preserve referencing in Loggly dashboard would not help much. Instead of this, it adds not required ids with the events which may confuse users.
```
ReferenceLoopHandling = ReferenceLoopHandling.Ignore
```

**Comment by psquickitjayant** [comment]
@giladwe, I have updated the reference loop handling to ignore loops by using the above mentioned code. The fix suggested by you was adding an extra id field to each object serialized by the library which is of no use in Loggly and can confuse Loggly users. It also increases the size of data sent to Loggly. Though, you can use your fork code to send logs to Loggly.

**Comment by giladwe** [comment]
Great!
when will this update be released on nuget?

**Comment by psquickitjayant** [comment]
Yes, added a beta version at https://www.nuget.org/packages/log4net-loggly/6.0.1-beta

**Pull request merged**
